services:
  postgres:
    image: postgres:latest
    container_name: nppk-postgres
    environment:
      POSTGRES_DB: nppk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nppk-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
